### ISSUE TITLE
Cannot run in node 4: SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by lrettig** [vinsonchuong/jasmine-es6#12]
Trying to run in node v4.3.2, I get the following error:

```
> node_modules/.bin/jasmine
node_modules/jasmine-es6/node_modules/dist-es6/node_modules/register-module/index.js:8
  for (const {name, path, main} of modules) {
             ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.runModule [as module] (node_modules/jasmine-es6/node_modules/dist-es6/lib/run.js:14:3)
    at _callee$ (node_modules/jasmine-es6/bin/jasmine.js:45:17)
    at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
```

Here is my `jasmine.json`:
```
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "../node_modules/jasmine-es6/lib/install.js",
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": true,
  "random": false
}
```

FYI the solution proposed in #4 did not work. Thanks.

**Comment by vinsonchuong** [comment]
Sorry for the late response. This package has been deprecated in favor of testing frameworks that have more support for Babel (like AVA and Mocha). If you prefer to use Jasmine, please use the original jasmine npm package and use a workaround such as https://gist.github.com/mauvm/172878a9646095d03fd7
