### ISSUE TITLE
Development tests fail

### ISSUE THREAD

**Issue by mauvm** [vinsonchuong/jasmine-es6#2]
``` bash
$ git clone https://github.com/vinsonchuong/jasmine-es6.git
$ cd jasmine-es6
$ npm install
$ npm test
> jasmine-es6@0.0.18 test /data/jasmine-es6
> eslint && jasmine

module.js:339
    throw err;
    ^

Error: Cannot find module '/data/jasmine-es6/spec/support/jasmine.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Jasmine.loadConfigFile (/data/jasmine-es6/node_modules/jasmine/lib/jasmine.js:75:16)
    at runJasmine (/data/jasmine-es6/node_modules/jasmine/lib/command.js:85:11)
    at Command.run (/data/jasmine-es6/node_modules/jasmine/lib/command.js:49:7)
    at Object.<anonymous> (/data/jasmine-es6/node_modules/jasmine/bin/jasmine.js:11:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
npm info jasmine-es6@0.0.18 Failed to exec test script
npm ERR! Test failed.  See above for more details.
```

Running `node:4.2.1` Docker container (NPM v2.14.7).

**Comment by vinsonchuong** [comment]
Hello, I apologize for being unresponsive. I'll try to keep on top of GitHub issues moving forward.

I don't know if this problem still persists for you; so, I'll close this issue for now. The test case shown works for me on Arch Linux with node 5.9.1 and npm 3.8.3.
